import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import ts from "typescript";
const source = await readFile(new URL("../src/delivery/transferScheduler.ts", import.meta.url), "utf8");
const compiled = ts.transpileModule(source, { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ES2022 } }).outputText;
const { acquireTransferSlot } = await import(`data:text/javascript;base64,${Buffer.from(compiled).toString("base64")}`);
test("执行线程有界，排队取消不占额度，释放操作可重复", async () => {
  const first = await acquireTransferSlot();
  const second = await acquireTransferSlot();
  const controller = new AbortController();
  const canceled = acquireTransferSlot(controller.signal);
  let started = false;
  const next = acquireTransferSlot().then(release => { started = true; return release; });
  await Promise.resolve();
  assert.equal(started, false);
  controller.abort();
  await assert.rejects(canceled, { name: "AbortError" });
  first(); first();
  const third = await next;
  assert.equal(started, true);
  let extra = false;
  const later = acquireTransferSlot().then(release => { extra = true; return release; });
  await Promise.resolve();
  assert.equal(extra, false);
  second();
  const fourth = await later;
  third(); fourth();
});
